feat: 모아보기 - 경험분해
depromeet/InsightOut-client pull request #84
Opened 2023-06-17 08:39 UTC by harseille

### 이슈 번호

depromeet/13th-4team-client#

### 작업 분류

- [ ] 버그 수정
- [x] 신규 기능
- [ ] 프로젝트 구조 변경

### 작업 상세 내용
- 기본 layout
- Chip list UI
- 겸험카드 마크업

2023-06-25 14:10 UTC, minkyung00 reviewed
고생하셨습니다!! 👍✨

근데 리뷰가 좀 많습니다.......... 하하..🗿

2023-06-25 14:10 UTC, newminkyung commented on src/app/collection/experiences/page.tsx
> +  const [selectedCapacityId, setSelectedCapacityId] = useState(shownCapabilities[0].id);
`getAllCapacityBadgeItem(capabilities)`랑 `shownCapabilities[0]` 둘 다 '전체'를 의미하는건가요?!

그렇다면 변수로 만들어서 재사용해도 좋을 것 같습니다~

2023-06-25 14:10 UTC, newminkyung commented on src/app/collection/experiences/page.tsx
> +  const [isSortedByUpdatedAt, setIsSortedByUpdatedAt] = useState(false);
새로운 정렬 방식이 추가될 가능성은 없을까요?! 

현재는 2가지 방식이라서 boolean으로 관리하고 계신 것 같은데 추후에 필터가 하나 더 추가되면 방식을 변경해야겠네요!

2023-06-25 14:10 UTC, newminkyung commented on src/app/collection/experiences/page.tsx
> +  const getFilterExperiencesBySelecedId = (experiences: Experience[], selectedCapacityId: number) => {
```suggestion
  const getFilterExperiencesBySelectedId = (experiences: Experience[], selectedCapacityId: number) => {
```

오타입니다👀

2023-06-25 14:10 UTC, newminkyung commented on src/app/collection/experiences/page.tsx
> +    return selectedCapacityId === 0
`0`을 변수로 분리한 '전체'의 id로 바꿔주시면 가독성이 더 좋아질 것 같아요! 

현재는 0이 어떤 걸 의미하는지 한 눈에 파악하기 어려운 것 같습니다~!

2023-06-25 14:10 UTC, newminkyung commented on src/app/collection/experiences/page.tsx
> +  const _experiences = getFilterExperiencesBySelecedId(experiences, selectedCapacityId);
filteredExperience라고 해도 괜찮지 않을까요..?!

2023-06-25 14:10 UTC, newminkyung commented on src/app/collection/experiences/page.tsx
> +  const __experiences = getSortedExperienceByExperienceTimeFilter(_experiences, isSortedByUpdatedAt);
sortedExperience라고 해도 괜찮지 않을까요...?!

2023-06-25 14:10 UTC, newminkyung commented on src/app/collection/experiences/page.tsx
> +        </nav>
이 부분 자기소개서 작성 부분에서도 사용해서 컴포넌트로 분리해주시면 감사하겠습니다..ㅎㅎ 🙇

2023-06-25 14:10 UTC, newminkyung commented on src/app/collection/experiences/page.tsx
> +  const EXPERIENCE_FILTER_BY_TIME = ['경험시간순', '작성시간순'];
배열로 관리하는 것보다 객체로 관리하는건 어떨까요?!

배열은 순서에 종속적이라서 어떤 값이 들어가있는지 파악하기 어려울 것 같습니다..!

2023-06-25 14:10 UTC, newminkyung commented on src/features/collection/components/cards/ExperienceCard.tsx
> +            <span className="mb-4 subhead4">직무영략 키워드</span>
```suggestion
            <span className="mb-4 subhead4">직무역량 키워드</span>
```

2023-06-25 14:10 UTC, newminkyung commented on src/features/collection/components/cards/ExperienceCard.tsx
> +  const { isOpen, onOpen, onClose } = useDisclosure();
아래 코드처럼 어떤 모달이 열리는지 뒤에 작성해주시면 좋을 것 같습니다 👍👍

하나의 페이지에서 여러 모달을 사용하다보니 어떤건지 명시해주면 굿..

2023-06-25 14:10 UTC, newminkyung commented on src/features/collection/components/cards/ExperienceCard.tsx
> +          {/* 카드 이미지 */}
주석으로 남겨주신 것들 컴포넌트로 분리하는거 어떻게 생각하세요?!


지금 주석을 작성하신게 마크업을 파악하기 어렵다는걸 보여주는 것 같은데요~! 네임스페이스 역할만 하더라도 분리해보는 것도 좋을 것 같다는 의견 제안해봅니다 👀

2023-06-25 14:10 UTC, newminkyung commented on src/features/collection/components/cards/ExperienceCard.tsx
> +        <div className="border-t-[1px] border-gray-200 my-[16px]"></div>
chakra에서 제공하는 `<Divider />` 사용해도 좋을 것 같습니다!

- https://chakra-ui.com/docs/components/divider/usage

2023-06-25 14:10 UTC, newminkyung commented on src/features/collection/components/cards/ExperienceModalCard.tsx
> +  const { isOpen, onClose, period, title, summaries, capabilities } = props;
```suggestion
const ExperienceModalCard = ({ isOpen, onClose, period, title, summaries, capabilities }: Props) => {
```

구조 분해 할당해서 코드 한 줄 줄여봅시다..!

2023-06-25 14:10 UTC, newminkyung commented on src/features/collection/components/cards/ExperienceCard.tsx
> +                .filter(({ isAi }) => !isAi)
ExperienceModalCard에서는 `const userCapabilitis = capabilities.filter(({ isAi }) => !isAi);` 로 사용하고 있더라구요!

저는 개인적으로 ExperienceModalCard에서 사용한 변수로 분리하는 방식이 더 좋은 것 같습니다..! 변수 이름만 보고 내용을 바로 파악할 수 있으면 좋을 것 같아요👀

2023-06-25 14:10 UTC, newminkyung commented on src/features/collection/components/cards/ExperienceModalCard.tsx
> +  const userCapabilitis = capabilities.filter(({ isAi }) => !isAi);
```suggestion
  const userCapabilities = capabilities.filter(({ isAi }) => !isAi);
```

2023-06-25 14:10 UTC, newminkyung commented on src/features/collection/types/index.ts
> +  experienceStatus: 'INPROGRESS' | 'DONE'; // boolean으로 수정하는건 어떨까?
차라리 서버 쪽에서 수정하는게 낫지 않을까요?! 

개인적으로 status에 boolean 값이 들어있는건 어색한 것 같습니다!

2023-06-25 14:10 UTC, newminkyung commented on src/features/collection/utils/getExperiencePeriod.ts
> +  const start = dayjs(startDate).format('YYYY.MM');
호오.. day.js를 사용하면 이렇게 간단하게 되는군요 👍👍
또 저 혼자 getFullYear 이런거 쓰고 있었네요..🗿

2023-06-25 14:10 UTC, newminkyung commented on src/shared/utils/addPlusMarkOver99.ts
> +const addPlusMarkOver99 = (target: string | number) => (Number(target) / 99 > 1 ? '99+' : target.toString());
99로 왜 나누는지 알 수 있을까요?!

`Number(target) > 99`랑 어떤게 다른건지 궁금합니다!

2023-06-25 14:10 UTC, minkyung00 commented on public/images/card1.png
스~~~~~~~~~~~~~~껄😎

2023-06-25 14:10 UTC, minkyung00 commented on src/components/Icon/IconClock.tsx
이거 저번에도 말씀드렸긴한디

1. public/icons에 svg 파일 넣고
2. yarn icon 실행하시면 

바~로 svgr에서 아이콘 컴포넌트 만들어줍니다.. 쏘 편리..👍

pacakge.json에 icon 명령어 보시면 바로 이해 가넝합니다!

2023-06-26 13:31 UTC, harseille commented on src/app/collection/experiences/page.tsx
> +  const [selectedCapacityId, setSelectedCapacityId] = useState(shownCapabilities[0].id);
좋은 포인트 감사합니다~ 추가적으로 함수를 utils로 분리하고 변수로 재사용하는 방법으로 수정하겠습니다!

2023-06-26 13:33 UTC, harseille commented on src/app/collection/experiences/page.tsx
> +  const [isSortedByUpdatedAt, setIsSortedByUpdatedAt] = useState(false);
기획적으로 논의 된 문제는 아니지만 만약 기획이 수정되거나 다른 ui로 변경 되면서 필터링이 추가 수도 있다는 것을 생각해봤을때를 생각해서 객체로 관리하는 것이 좋아보이네요~

2023-06-26 13:44 UTC, sangbooom commented on src/app/collection/experiences/page.tsx
> +      updatedAt: '2023-04-01T00:00:00.000Z',
경험분해 조회받으실때 Date타입으로 전달안받고 YYYY-MM 으로 전달받는거 아닌가요?! 스웨거에서 어떤 api로 받으시나요?

2023-06-26 13:44 UTC, sangbooom commented on src/app/collection/experiences/page.tsx
> +  const getSortedExperienceByExperienceTimeFilter = (experiences: Experience[], isSortedByUpdatedAt: boolean) =>
함수네이밍이 잘 안읽히네요 😭 더 직관인 네이밍으로 변경해도 좋을 것 같아요! 
추가적으로 Filter라는 이름때문에 filter로 오해할 수 있을 것 같습니다

2023-06-26 13:44 UTC, sangbooom commented on src/app/collection/experiences/page.tsx
> +  const getSortedExperienceByExperienceTimeFilter = (experiences: Experience[], isSortedByUpdatedAt: boolean) =>
experiences 라는 prop만 array로 변경되어도 함수네이밍이 더 간단해질 것 같습니다. 
또한 경험분해 도메인이 묻지않아 결합도가 낮아지고 다른 컴포넌트에서도 재사용 가능할 것 같네요~

2023-06-26 13:44 UTC, sangbooom commented on src/components/Button/TextButton.module.scss
> +// }
이건 주석처리하신 이유가 있으신가요?

2023-06-26 13:44 UTC, sangbooom commented on src/components/Icon/IconClock.tsx
> +);
일관성 있게 svgr로 컴포넌트화 시켜주시면 감사하겠습니다~

2023-06-26 13:44 UTC, sangbooom commented on src/features/collection/components/cards/ExperienceCard.tsx
> +          console.log('test');
불필요한 로그는 제거 부탁드립니다~!

2023-06-26 13:44 UTC, sangbooom commented on src/features/collection/components/cards/ExperienceCard.tsx
> +            console.log('삭제하기');
로그 제거부탁드립니다~

2023-06-26 13:44 UTC, sangbooom commented on src/features/collection/components/cards/ExperienceModalCard.tsx
> +                  {!isBack ? '카드 뒷면보기' : '카드 앞면보기'}
```suggestion
                  {isBack ? '카드 앞면보기' : '카드 뒷면보기'}
```
개인적으로 안티패턴이라고 생각합니다~

2023-06-26 13:44 UTC, sangbooom commented on src/features/collection/components/cards/ExperienceModalCard.tsx
> +              {!isBack ? (
여기도 상동입니다~

2023-06-26 13:44 UTC, sangbooom commented on src/features/collection/components/cards/ExperienceModalCard.tsx
> +};
컴포넌트화를 해서 가독성을 높히면 좋을 것 같아요~

2023-06-26 13:44 UTC, sangbooom commented on yarn.lock
> +dayjs@^1.11.8:
dayjs를 선택하신 이유가 궁금합니다~~ 👀

2023-06-26 13:44 UTC, sangbooom commented on src/features/resume/components/LeftNavigationBar/Resume/ResumeItem/Title.tsx
> +            onKeyUp={handleEditInputEnterKeyPress}
keyUp 이벤트인데 함수네이밍은 keyPress네요 😵‍💫 변경부탁드립니다~

2023-06-26 13:44 UTC, sangbooom commented on src/features/resume/components/LeftNavigationBar/Resume/ResumeItem/Title.tsx
> +  };
onClick 이벤트 버블링을 캡처링으로 변경해도 좋을 것 같은데 어떻게 생각하시나요~?

2023-06-26 13:48 UTC, sangbooom requested changes
전체적으로 코드양이 많은것도 많은건데 컴포넌트별로 분리가 되지 않은 부분들이 많아서 솔직히 리뷰하기 힘들긴하네요 😅 좀 더 코드 정리를 해주신다면 누군가 유지보수 할 때 편할 것 같습니다~

2023-06-26 13:51 UTC, harseille commented on src/app/collection/experiences/page.tsx
> +  const getFilterExperiencesBySelecedId = (experiences: Experience[], selectedCapacityId: number) => {
섬세한 리뷰 감사드립니다~~ 함수명이 너무 길어서 가독성이 좋지 않은 것 같아 오타 수정하면서 함수명도 변경하겠습니다!

2023-07-08 00:23 UTC, closed without merging